

### Variables 
@baseUrl = http://localhost:8080/parking

### Get List
GET {{baseUrl}} HTTP/1.1

### Get One 
GET {{baseUrl}}/caded58e8e0f4ccf99ceb3b131a15a5a HTTP/1.1

### Create
POST {{baseUrl}} HTTP/1.1
Content-Type: application/json

{
    "license": "REE-1234",
    "state": "SE",
    "model": "JETTA",
    "color": "CINZA"
}