

### Variables
@baseUrl = http://localhost:8080/parking
@client = cloud:p@rk!ng
@id = {{uuid.response.body.id}}

### Create one parking
# @name uuid
POST {{baseUrl}} HTTP/1.1
Authorization: Basic {{client}}
Content-Type: application/json

{
    "license": "REE-1234",
    "state": "SE",
    "model": "JETTA",
    "color": "CINZA"
}

### Update one parking
PUT {{baseUrl}}/{{id}} HTTP/1.1
Authorization: Basic {{client}}
Content-Type: application/json

{
    "license": "REE-1234",
    "state": "SP",
    "model": "JETTA",
    "color": "PRATA"
}

### Find all parkings
GET {{baseUrl}} HTTP/1.1
Authorization: Basic {{client}}

### Find one parking
GET {{baseUrl}}/{{id}} HTTP/1.1
Authorization: Basic {{client}}

### Checkout
POST {{baseUrl}}/{{id}} HTTP/1.1
Authorization: Basic {{client}}

### Delete one parking
DELETE  {{baseUrl}}/{{id}} HTTP/1.1
Authorization: Basic {{client}}