name: parking-control

services:
  api:
    build:
      context: .
      target: production
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
        required: true

  postgres:
    image: postgres:16-alpine3.19
    restart: unless-stopped
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

volumes:
  postgres:
