version: '3.4'

services:
  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: "exit 0"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    env_file:
      - .env
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
