version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - ${PORT:-8080}:8080
    networks:
      - net
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["./mvnw", "spring-boot:run"]

  postgres:
    image: postgres:10-alpine
    restart: unless-stopped
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    networks:
      - net
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: "exit 0"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - net
    env_file:
      - .env
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:

networks:
  net:
    name: parking-control
    driver: bridge