name: parking-control

services:
  api:
    build: .
    restart: unless-stopped
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
        required: true

  postgres:
    image: postgres:16-alpine3.19
    restart: unless-stopped
    env_file: .env
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

volumes:
  postgres:
