application:
  title: Cloud Parking
  description: Cloud Parking
  version: 1.0.0

springdoc:
  api-docs:
    version: openapi-3-0
    enabled: true

server:
  port: 8081
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/parking
    username: admin
    password: 6e96c406d6008575611293c6388a713

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  devtools:
    livereload:
      port: 35730
