springdoc:
  api-docs:
    enabled: true
    version: openapi-3-0

server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: Cloud Parking

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/parking
    username: admin
    password: 6e96c406d6008575611293c6388a713

  sql:
    init:
      mode: always

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  devtools:
    livereload:
      enabled: true
      port: 35730

logging:
  level:
    br:
      com:
        api: TRACE
