springdoc:
  api-docs:
    enabled: true
    version: openapi-3-0

server:
  port: 8081
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always

spring:
  application:
    name: Cloud Parking

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/parking
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  devtools:
    livereload:
      enabled: true
      port: 8082
    restart:
      enabled: true
      exclude: "META-INF/maven/**,META-INF/resources/**,static/**,public/**,templates/**,**/*Test.class,**/*Tests.class,git.properties,META-INF/build-info.properties"

logging:
  level:
    web: DEBUG
    br:
      com:
        api: TRACE
